<a href="https://colab.research.google.com/github/Usori/Talento-na-Nuvem/blob/main/Desenvolvimento_7_Condicionais_e_Aplica%C3%A7%C3%B5es_Victor_Hugo_Oliveira.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instruções
Desenvolva um código que utilize as seguintes características de um veículo:
- Quantidade de rodas;
- Peso bruto em quilogramas;
- Quantidade de pessoas no veículo.

Com essas informações, o programa mostrará qual é a melhor categoria de habilitação para o veículo informado a partir das condições:
- A: Veículos com duas ou três rodas;
- B: Veículos com quatro rodas, que acomodam até oito pessoas e seu peso é de até 3500 kg;
- C: Veículos com quatro rodas ou mais e com peso entre 3500 e 6000 kg;
- D: Veículos com quatro rodas ou mais e que acomodam mais de oito pessoas;
- E: Veículos com quatro rodas ou mais e com mais de 6000 kg.

In [1]:
import pandas as pd

In [5]:
def classificar_veiculo(row):

  nome, rodas, peso, qtd_pessoas, categoria = row

  if rodas == 2 or rodas == 3: # Veiculos com duas ou três rodas
    return 'A'

  elif rodas >= 4:
    # Veiculos com quatro rodas, que acomodam até oito pessoas e seu peso é de até 3500 kg;
    if rodas == 4 and peso <= 3500 and qtd_pessoas <= 8:
      return 'B'

    # Veículos com quatro rodas ou mais
    if peso >= 3500 and peso <= 6000 and qtd_pessoas <= 8: # e com peso entre 3500 e 6000 kg;
      return 'C'
    elif peso > 6000: # e que acomodam mais de oito pessoas;
      return 'D'
    elif qtd_pessoas > 8: # e com mais de 6000 kg.
      return 'E'
    else:
      return 'N'

  else:
    return 'N' # categoria não englobada

In [6]:
# Exemplo de uso da função apply() em um DataFrame

lista_veiculos = [
     ["Veiculo1", 4, 3000, 5, '']
    ,["Veiculo2", 2, 3500, 4, '']
    ,["Veiculo3", 1, 2400, 2, '']
    ,["Veiculo4", 5, 2700, 3, '']
    ,["Veiculo5", 8, 5000, 1, '']
    ,["Veiculo6", 3, 9000, 4, '']
    ,["Veiculo7", 2, 3600, 1, '']
    ,["Veiculo8", 6, 4200, 8, '']
    ,["Veiculo9", 2, 8100, 9, '']
]

df1 = pd.DataFrame(lista_veiculos, columns = ['Nome_Veiculo', 'Rodas', 'Peso', 'Qtd_Pessoas', 'Categoria'])
df1['Categoria'] = df1.apply(classificar_veiculo, axis=1)
df1

  Nome_Veiculo  Rodas  Peso  Qtd_Pessoas Categoria
0     Veiculo1      4  3000            5         B
1     Veiculo2      2  3500            4         A
2     Veiculo3      1  2400            2         N
3     Veiculo4      5  2700            3         N
4     Veiculo5      8  5000            1         C
5     Veiculo6      3  9000            4         A
6     Veiculo7      2  3600            1         A
7     Veiculo8      6  4200            8         C
8     Veiculo9      2  8100            9         A

In [8]:
# Casos de Teste

lista_teste = [
    ["Teste A1", 2, 2000, 1, '']
    ,["Teste A2", 2, 5000, 2, '']
    ,["Teste A3", 2, 7000, 8, '']
    ,["Teste A4", 3, 2000, 9, '']
    ,["Teste A5", 3, 5000, 2, '']
    ,["Teste A6", 3, 7000, 1, '']
    ,["Teste B - Pos1", 4, 1000, 8, '']
    ,["Teste B - Pos2", 4, 2000, 3, '']
    ,["Teste B - Pos2", 4, 3500, 5, '']
    ,["Teste B - Neg1", 4, 3501, 4, '']
    ,["Teste B - Neg2", 4, 1000, 9, '']
    ,["Teste C - Pos1", 4, 3501, 1, '']
    ,["Teste C - Pos2", 4, 5000, 1, '']
    ,["Teste C - Pos3", 4, 6000, 1, '']
    ,["Teste C - Pos4", 5, 3500, 1, '']
    ,["Teste C - Pos5", 5, 3500, 1, '']
    ,["Teste C - Pos6", 5, 3500, 1, '']
    ,["Teste C - Pos7", 4, 3501, 1, '']
    ,["Teste C - Pos8", 8, 3500, 1, '']
    ,["Teste C - Pos9", 10, 3500, 1, '']
    ,["Teste C - Pos10", 4, 3501, 4, '']
    ,["Teste C - Pos11", 8, 3500, 6, '']
    ,["Teste C - Pos12", 10, 3500, 8, '']
    ,["Teste C - Neg1", 4, 3500, 8, '']
    ,["Teste C - Neg2", 8, 6001, 1, '']
    ,["Teste D", 4, 12000, 1, '']
    ,["Teste E", 4, 6000, 20, '']
    ,["Teste N1", 1, 3500, 4, '']
    ,["Teste N2", 5, 2700, 3, '']
]

df2 = pd.DataFrame(lista_teste, columns = ['Nome_Veiculo', 'Rodas', 'Peso', 'Qtd_Pessoas', 'Categoria'])
df2['Categoria'] = df2.apply(classificar_veiculo, axis=1)
df2

       Nome_Veiculo  Rodas   Peso  Qtd_Pessoas Categoria
0          Teste A1      2   2000            1         A
1          Teste A2      2   5000            2         A
2          Teste A3      2   7000            8         A
3          Teste A4      3   2000            9         A
4          Teste A5      3   5000            2         A
5          Teste A6      3   7000            1         A
6    Teste B - Pos1      4   1000            8         B
7    Teste B - Pos2      4   2000            3         B
8    Teste B - Pos2      4   3500            5         B
9    Teste B - Neg1      4   3501            4         C
10   Teste B - Neg2      4   1000            9         E
11   Teste C - Pos1      4   3501            1         C
12   Teste C - Pos2      4   5000            1         C
13   Teste C - Pos3      4   6000            1         C
14   Teste C - Pos4      5   3500            1         C
15   Teste C - Pos5      5   3500            1         C
16   Teste C - Pos6      5   3500            1         C
17   Teste C - Pos7      4   3501            1         C
18   Teste C - Pos8      8   3500            1         C
19   Teste C - Pos9     10   3500            1         C
20  Teste C - Pos10      4   3501            4         C
21  Teste C - Pos11      8   3500            6         C
22  Teste C - Pos12     10   3500            8         C
23   Teste C - Neg1      4   3500            8         B
24   Teste C - Neg2      8   6001            1         D
25          Teste D      4  12000            1         D
26          Teste E      4   6000           20         E
27         Teste N1      1   3500            4         N
28         Teste N2      5   2700            3         N